[build-system]
requires = ["setuptools>=61", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "cocotbext-spi"
description = "SPI modules for cocotb"
authors = [
    {name = "Spencer Chang", email = "spencer@sycee.xyz"},
]
dependencies = [
    "cocotb>=1.6",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)",
]
requires-python = ">=3.7"
readme = "README.md"
license = {text = "MIT"}
dynamic = ["version"]

[tool.setuptools_scm]
write_to = "cocotbext/spi/_version.py"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]
addopts = "--import-mode importlib"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py{37,38,39},lint

[testenv]
setenv =
    PDM_IGNORE_SAVED_PYTHON="1"
deps = pdm
commands =
    pdm install --dev
    pytest tests -n auto

[testenv:lint]
deps = pdm
commands =
    pdm install -G lint
    flake8 cocotbext/ tests/
"""

[tool.pdm]
[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.2.1",
    "cocotb-test>=0.2.4",
    "pytest-xdist>=3.2.0",
]
lint = [
    "flake8>=5.0.4",
]
